if(EXISTS "/home/jonahr/Documents/Code/CCPP/neows_visualization/Tests-b12d07c_tests.cmake")
  include("/home/jonahr/Documents/Code/CCPP/neows_visualization/Tests-b12d07c_tests.cmake")
else()
  add_test(Tests_NOT_BUILT-b12d07c Tests_NOT_BUILT-b12d07c)
endif()
